ALTER TYPE "AdminRole" RENAME VALUE 'approver' TO 'operator';

ALTER TABLE "AdminUser"
  ADD COLUMN "active" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
